### ISSUE TITLE
Exception error thrown in unregisteration

### ISSUE THREAD

**Issue by tetii** [nutti/Index-Visualizer#1]
Bug:
**AttributeError** was thrown when I turned on the starting button and then disabled the addon. 
```
Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\space_view3d_index_visualizer.py", line 212, in render_indices
    IVRenderer.__render_data(context, rendered_data)
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\space_view3d_index_visualizer.py", line 103, in __render_data
    IVRenderer.__render_each_data(context, d)
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\space_view3d_index_visualizer.py", line 129, in __render_each_data
    rect = get_canvas(context, loc_on_screen, len(str(data[0])), sc.iv_font_size)
AttributeError: 'Scene' object has no attribute 'iv_font_size'

```
Recommendation: 
I recommend removing the handle before calling unregister_module function.

**Comment by nutti** [comment]
@tetii 

Thanks for bug report. I will fix this bug in future.
You can also send me a pull request if you are willing to fix this bug.
You have enough experience to fix this bug.

**Comment by nutti** [comment]
Thanks for your contribution.
Your fix is merged, so I will close it.
